### ISSUE TITLE
Gave up on multiplayer? I may be able to help with custom server using python

### ISSUE THREAD

**Issue by RaSan147** [coolst3r/life-is-a-game#1]
You did saw my voiceAI asuna. No introduction needed. 😅
I'll try compiling it on my pc

**Comment by RaSan147** [comment]
Oh seems you've already tried adding server. Don't mind me

**Comment by s-b-repo** [comment]
> Oh seems you've already tried adding server. Don't mind me

i can give you the game im gunna make it open source so

**Comment by s-b-repo** [comment]
> Oh seems you've already tried adding server. Don't mind me
https://thememegang.itch.io/cringe-boi
